name: Build Binaries

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2025-vs2026
    env:
      POWERSHELL_TELEMETRY_OPTOUT: 1
    steps:
    - uses: actions/checkout@v6
      with:
        submodules: 'recursive'
    - uses: microsoft/setup-msbuild@v3
    - name: Clear local NuGet cache (workaround for failed restores on windows-latest)
      run: dotnet nuget locals all --clear
    - name: Build
      run: |
        $env:_CL_=" /GF /Gw /Gy /GL /Ox /Ob3 /Oi /Ot /Oy /Z7 /MT /fp:fast /fpcvt:IA /jumptablerdata /arch:AVX512 /vlen=512 /w /d2epilogunwind /volatileMetadata-"
        $env:_LINK_=" /LTCG:INCREMENTAL /opt:ref,icf /filealign:4096 /release /nodefaultlib:libucrt.lib /defaultlib:ucrt.lib /osversion:10.0 /Brepro"
        MSBuild -binaryLogger:Output\BuildAllTargets.binlog -m BuildAllTargets.proj /p:Configuration=Release /p:platformToolset=v145 /p:Platform=x64 /p:PreferredToolArchitecture=x64 /p:DebugSymbols=false /p:DebugType=None /p:DebugInformationFormat=0
    - name: Upload MSIX Bundle
      uses: actions/upload-artifact@v7
      with:
        name: NanaZip_Mainline_ApplicationPackages
        path: Output/Binaries/AppPackages
